services:
  proxy:
    container_name: proxy-app
    image: nginx:latest
    volumes:
      - ./proxy_conf/:/etc/nginx/conf.d/
    depends_on:
      - nginx
    ports:
      - "80:80"

  nginx:
    container_name: nginx-app
    image: nginx:latest
    volumes:
      - ./nginx_conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx_conf/fastcgi.conf/:/etc/nginx/fastcgi.conf
    depends_on:
      - backend
    ports:
      - "80"

  backend:
    container_name: backend-app
    build:
      context: ./www
      dockerfile: ../Dockerfile.backend
    volumes:
      - ./www/backend:/var/www/backend
    ports:
      - "9000"


